### ISSUE TITLE
XBox Series X Share Button remap don't work.

### ISSUE THREAD

**Issue by V3ntilator** [Adam777Z/xbox-controller-button-remapper#7]
Hello!

I can't get Series X Share button to work with this program.
What i tried is this.

share_key = 56,68 (ALT+F10) remap to Share Button on Series X pad.
ALT+F10 is my hotkey for NVIDIA Shadowplay recording.

I enabled debug mode. It registers button presses, but don't register Share button at all.

EDIT: I finally found some generic info. Windows 10 don't support Share button, but Steam detects it so you can remap it.

**Comment by Adam777Z** [comment]
This program works on Windows 10/11 64-bit to remap the Xbox/Guide button and/or Share button on the Xbox Controller.

Support is available under [Discussions](https://github.com/Adam777Z/xbox-controller-button-remapper/discussions) in [Help](https://github.com/Adam777Z/xbox-controller-button-remapper/discussions/2).
